export default [
    {
        id: 1,
        username: 'aronbergman',
        email: 'brgmn@icloud.com',
        typeOfApplicant: 0,
        typeOfObject: 'room',
        sizeOfObject: 4,
        city: 78,
        metroStations: null,
        distanceMetro: null,
        description: null,
        price: null,
        floor: null,
        infrastructure: null,
        deposit: null,
        renovation: '2',
        active: 1,
        userId: 1,
        createdAt: '2020-05-07T20:03:43.000Z',
        updatedAt: '2020-05-07T20:03:43.000Z'
    },
    {
        id: 2,
        username: 'aronbergmghtjykuian',
        email: 'brgmn@icloud.com',
        typeOfApplicant: 0,
        typeOfObject: 'room',
        sizeOfObject: 4,
        city: 77,
        metroStations: null,
        distanceMetro: null,
        description: null,
        price: null,
        floor: null,
        infrastructure: null,
        deposit: null,
        renovation: '2',
        active: 1,
        userId: 1,
        createdAt: '2020-05-07T20:03:43.000Z',
        updatedAt: '2020-05-07T20:03:43.000Z'
    },
    {
        id: 3,
        username: 'gthsryju',
        email: 'brgmn@icloud.com',
        typeOfApplicant: 0,
        typeOfObject: 'room',
        sizeOfObject: 4,
        city: 77,
        metroStations: null,
        distanceMetro: null,
        description: null,
        price: null,
        floor: null,
        infrastructure: null,
        deposit: null,
        renovation: '2',
        active: 1,
        userId: 1,
        createdAt: '2020-05-07T20:03:43.000Z',
        updatedAt: '2020-05-07T20:03:43.000Z'
    }
]